channels:
- conda-forge
- bioconda
dependencies:
- bioconda::liftover=1.3.3
- bioconda::pybedtools==0.12.0
- bioconda::pybigwig==0.3.22
- bioconda::cyvcf2==0.31.0
- conda-forge::python=3.10.20
- conda-forge::numpy==1.26.4
- conda-forge::pandas==2.3.3
- conda-forge::joblib==1.5.3
- conda-forge::scikit-learn==1.0.2